### ISSUE TITLE
Name for subscribers video (or incoming videos)

### ISSUE THREAD

**Issue by sumagowda** [josecpujol/opentok3d#7]
Hello there,
How do I set name for the subscribers video (or incoming video).....so that its easy to identify who is who while on a group video call.
Please advice.
Thanks for all the great work.
Regards,
Suma

**Comment by josecpujol** [comment]
When creating a publisher, you can pass as a property the name of that person. In the subscriber, you can access that name property through the stream object

Check https://tokbox.com/developer/sdks/js/reference/Publisher.html on how to set the name of the publisher (it is in the example) and https://tokbox.com/developer/sdks/js/reference/Stream.html, where it is explained how to access the name property in the stream object.

**Comment by sumagowda** [comment]
Hi Jose,
Thanks for the prompt response. To be specific....how do I add name to the
tween-camera object the one that shows up in function addClient()
.....thats the object I am not able to add name to.
The main publisher widget shows name and controls correctly. Its the
tweened camera object I am not able to display name for.
If you can add it to your demo that would be big help.
Pls advice.
Thx.

**Comment by josecpujol** [comment]
Oh, you mean to actually display the name?
Well, with webgl, we are not in the "html" world anymore, and displaying stuff must be done in the webgl domain. The original publisher widget is in that html world, so all it's goodies (like icons, name display, etc) are lost as soon as we decided to move to webgl
Since we are taking the video to create a texture, you need to paint in the geometry devoted to contain that texture. I suggest you create a new texture with the name on it and combine the two textures. That texture with the name needs to have the alpha channel on, so the name is displayed on top of the video, but the video is shown outside the name.

Three.js has some tools to create textures from text:
* http://learningthreejs.com/blog/2014/05/02/easy-to-use-dynamic-texture-to-write-text-in-your-3d-object-with-threex-dot-dynamictexture-game-extensions-for-three-dot-js/
* http://stackoverflow.com/questions/12380072/threejs-render-text-in-canvas-as-texture-and-then-apply-to-a-plane

Feel free to create a pull request

**Comment by sumagowda** [comment]
Thank you Jose. I appreciate your response and for maintaining this code on
github.

**Comment by josecpujol** [comment]
np. Closing the issue
